name: find_pharma
description: "Application mobile de géolocalisation de pharmacies et d'assistant de santé intelligent."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  cloud_firestore: ^6.10.0
  dio: ^5.11.1
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.1
  hive_flutter: ^1.1.0
  intl: ^0.20.3
  rename_app: ^1.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/

config_name:
  name: "Find Pharma"

flutter_native_splash:
  color: "#F4FAF6"
  image: assets/images/find_pharma_splash.png
  fullscreen: true                
  #! ANDROID 12+ configuration:
  android_12:
    color: "#F4FAF6"
    image: assets/images/find_pharma_icon.png
    icon_background_color: "#F4FAF6"
