// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrhzypS3FJgfMEOBTblCzr512fPq0Vzk',
    appId: '1:324086752278:web:02b4b7b800d8d4a9e14137',
    messagingSenderId: '324086752278',
    projectId: 'find-pharma-f9151',
    authDomain: 'find-pharma-f9151.firebaseapp.com',
    storageBucket: 'find-pharma-f9151.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZFu6AIIUOQMYkJSBFa7OkftmLeAG1pM',
    appId: '1:324086752278:android:2226501b71aeb8c7e14137',
    messagingSenderId: '324086752278',
    projectId: 'find-pharma-f9151',
    storageBucket: 'find-pharma-f9151.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplanXfZjEsuIGCVig7qW-gZZxevgNYuY',
    appId: '1:324086752278:ios:a582855f17efc98ee14137',
    messagingSenderId: '324086752278',
    projectId: 'find-pharma-f9151',
    storageBucket: 'find-pharma-f9151.firebasestorage.app',
    iosBundleId: 'com.findpharmag9.org.findPharma',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDplanXfZjEsuIGCVig7qW-gZZxevgNYuY',
    appId: '1:324086752278:ios:a582855f17efc98ee14137',
    messagingSenderId: '324086752278',
    projectId: 'find-pharma-f9151',
    storageBucket: 'find-pharma-f9151.firebasestorage.app',
    iosBundleId: 'com.findpharmag9.org.findPharma',
  );
}
